### ISSUE TITLE
Output immutable instance labels

### ISSUE THREAD

**Issue by fatmcgav** [elastic/runbld#172]
In the brave new world of immutable dynamic Jenkins workers, knowing what version of a specific image was used to run that build becomes more important to be able to debug any failures etc. 

To that end, the GCP images are _tagged_ with a set of `labels` which provide pertentant information. 

For example:
```
gcloud beta compute images describe elastic-foundation-centos-7-20180913131825
archiveSizeBytes: '917517568'
creationTimestamp: '2018-09-13T06:25:03.429-07:00'
description: Created by Packer
diskSizeGb: '10'
family: elastic-foundation-centos-7
id: '1133658114662849472'
kind: compute#image
labelFingerprint: 2BplojtY8uE=
labels:
  build_number: '83'
  built_by: packer_builder
  git_branch: origin-master
  git_commit: 5f39d33b17d51c2857f05460717f2350bc2265df
licenseCodes:
- '1000207'
licenses:
- https://www.googleapis.com/compute/beta/projects/centos-cloud/global/licenses/centos-7
name: elastic-foundation-centos-7-20180913131825
selfLink: https://www.googleapis.com/compute/beta/projects/elastic-images-prod/global/images/elastic-foundation-centos-7-20180913131825
sourceDisk: https://www.googleapis.com/compute/beta/projects/elastic-images-prod/zones/us-central1-a/disks/packer-5b9a63a1-4962-097b-396a-58031ac7d9b4
sourceDiskId: '596821270343441740'
sourceType: RAW
status: READY
```

The useful bits here are the `labels`, as they confirm what `git_commit` was used to build the image.

It would be useful if `runbld` could output some of this information at the start of a build in a similar fashion to it's version number output. 
Suggested fields:
* `family`
* `name`
* `label.git_commit`
* `label.build_number` 

cc @Crazybus / @elasticdog
